/*
 * Argo Workflows API
 *
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argo-workflows.readthedocs.io/en/latest/
 *
 * The version of the OpenAPI document: VERSION
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GithubComArgoprojArgoEventsPkgApisEventsV1alpha1Backoff {
    #[serde(rename = "duration", skip_serializing_if = "Option::is_none")]
    pub duration: Option<Box<models::GithubComArgoprojArgoEventsPkgApisEventsV1alpha1Int64OrString>>,
    #[serde(rename = "factor", skip_serializing_if = "Option::is_none")]
    pub factor: Option<Box<models::GithubComArgoprojArgoEventsPkgApisEventsV1alpha1Amount>>,
    #[serde(rename = "jitter", skip_serializing_if = "Option::is_none")]
    pub jitter: Option<Box<models::GithubComArgoprojArgoEventsPkgApisEventsV1alpha1Amount>>,
    #[serde(rename = "steps", skip_serializing_if = "Option::is_none")]
    pub steps: Option<i32>,
}

impl GithubComArgoprojArgoEventsPkgApisEventsV1alpha1Backoff {
    pub fn new() -> GithubComArgoprojArgoEventsPkgApisEventsV1alpha1Backoff {
        GithubComArgoprojArgoEventsPkgApisEventsV1alpha1Backoff {
            duration: None,
            factor: None,
            jitter: None,
            steps: None,
        }
    }
}

