/*
 * Argo Workflows API
 *
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argo-workflows.readthedocs.io/en/latest/
 *
 * The version of the OpenAPI document: VERSION
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GithubComArgoprojArgoEventsPkgApisEventsV1alpha1Trigger {
    #[serde(rename = "atLeastOnce", skip_serializing_if = "Option::is_none")]
    pub at_least_once: Option<bool>,
    #[serde(rename = "dlqTrigger", skip_serializing_if = "Option::is_none")]
    pub dlq_trigger: Option<Box<models::GithubComArgoprojArgoEventsPkgApisEventsV1alpha1Trigger>>,
    #[serde(rename = "parameters", skip_serializing_if = "Option::is_none")]
    pub parameters: Option<Vec<models::GithubComArgoprojArgoEventsPkgApisEventsV1alpha1TriggerParameter>>,
    #[serde(rename = "policy", skip_serializing_if = "Option::is_none")]
    pub policy: Option<Box<models::GithubComArgoprojArgoEventsPkgApisEventsV1alpha1TriggerPolicy>>,
    #[serde(rename = "rateLimit", skip_serializing_if = "Option::is_none")]
    pub rate_limit: Option<Box<models::GithubComArgoprojArgoEventsPkgApisEventsV1alpha1RateLimit>>,
    #[serde(rename = "retryStrategy", skip_serializing_if = "Option::is_none")]
    pub retry_strategy: Option<Box<models::GithubComArgoprojArgoEventsPkgApisEventsV1alpha1Backoff>>,
    #[serde(rename = "template", skip_serializing_if = "Option::is_none")]
    pub template: Option<Box<models::GithubComArgoprojArgoEventsPkgApisEventsV1alpha1TriggerTemplate>>,
}

impl GithubComArgoprojArgoEventsPkgApisEventsV1alpha1Trigger {
    pub fn new() -> GithubComArgoprojArgoEventsPkgApisEventsV1alpha1Trigger {
        GithubComArgoprojArgoEventsPkgApisEventsV1alpha1Trigger {
            at_least_once: None,
            dlq_trigger: None,
            parameters: None,
            policy: None,
            rate_limit: None,
            retry_strategy: None,
            template: None,
        }
    }
}

