/*
 * Argo Workflows API
 *
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argo-workflows.readthedocs.io/en/latest/
 *
 * The version of the OpenAPI document: VERSION
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GithubComArgoprojArgoEventsPkgApisEventsV1alpha1AzureServiceBusTrigger {
    #[serde(rename = "connectionString", skip_serializing_if = "Option::is_none")]
    pub connection_string: Option<Box<models::IoK8sApiCoreV1SecretKeySelector>>,
    #[serde(rename = "parameters", skip_serializing_if = "Option::is_none")]
    pub parameters: Option<Vec<models::GithubComArgoprojArgoEventsPkgApisEventsV1alpha1TriggerParameter>>,
    /// Payload is the list of key-value extracted from an event payload to construct the request payload.
    #[serde(rename = "payload", skip_serializing_if = "Option::is_none")]
    pub payload: Option<Vec<models::GithubComArgoprojArgoEventsPkgApisEventsV1alpha1TriggerParameter>>,
    #[serde(rename = "queueName", skip_serializing_if = "Option::is_none")]
    pub queue_name: Option<String>,
    #[serde(rename = "subscriptionName", skip_serializing_if = "Option::is_none")]
    pub subscription_name: Option<String>,
    #[serde(rename = "tls", skip_serializing_if = "Option::is_none")]
    pub tls: Option<Box<models::GithubComArgoprojArgoEventsPkgApisEventsV1alpha1TlsConfig>>,
    #[serde(rename = "topicName", skip_serializing_if = "Option::is_none")]
    pub topic_name: Option<String>,
}

impl GithubComArgoprojArgoEventsPkgApisEventsV1alpha1AzureServiceBusTrigger {
    pub fn new() -> GithubComArgoprojArgoEventsPkgApisEventsV1alpha1AzureServiceBusTrigger {
        GithubComArgoprojArgoEventsPkgApisEventsV1alpha1AzureServiceBusTrigger {
            connection_string: None,
            parameters: None,
            payload: None,
            queue_name: None,
            subscription_name: None,
            tls: None,
            topic_name: None,
        }
    }
}

