/*
 * Argo Workflows API
 *
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argo-workflows.readthedocs.io/en/latest/
 *
 * The version of the OpenAPI document: VERSION
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GithubComArgoprojArgoEventsPkgApisEventsV1alpha1Container {
    #[serde(rename = "env", skip_serializing_if = "Option::is_none")]
    pub env: Option<Vec<models::IoK8sApiCoreV1EnvVar>>,
    #[serde(rename = "envFrom", skip_serializing_if = "Option::is_none")]
    pub env_from: Option<Vec<models::IoK8sApiCoreV1EnvFromSource>>,
    #[serde(rename = "imagePullPolicy", skip_serializing_if = "Option::is_none")]
    pub image_pull_policy: Option<String>,
    #[serde(rename = "resources", skip_serializing_if = "Option::is_none")]
    pub resources: Option<Box<models::IoK8sApiCoreV1ResourceRequirements>>,
    #[serde(rename = "securityContext", skip_serializing_if = "Option::is_none")]
    pub security_context: Option<Box<models::IoK8sApiCoreV1SecurityContext>>,
    #[serde(rename = "volumeMounts", skip_serializing_if = "Option::is_none")]
    pub volume_mounts: Option<Vec<models::IoK8sApiCoreV1VolumeMount>>,
}

impl GithubComArgoprojArgoEventsPkgApisEventsV1alpha1Container {
    pub fn new() -> GithubComArgoprojArgoEventsPkgApisEventsV1alpha1Container {
        GithubComArgoprojArgoEventsPkgApisEventsV1alpha1Container {
            env: None,
            env_from: None,
            image_pull_policy: None,
            resources: None,
            security_context: None,
            volume_mounts: None,
        }
    }
}

