/*
 * Argo Workflows API
 *
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argo-workflows.readthedocs.io/en/latest/
 *
 * The version of the OpenAPI document: VERSION
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// GithubComArgoprojArgoEventsPkgApisEventsV1alpha1SensorStatus : SensorStatus contains information about the status of a sensor.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GithubComArgoprojArgoEventsPkgApisEventsV1alpha1SensorStatus {
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<Box<models::GithubComArgoprojArgoEventsPkgApisEventsV1alpha1Status>>,
}

impl GithubComArgoprojArgoEventsPkgApisEventsV1alpha1SensorStatus {
    /// SensorStatus contains information about the status of a sensor.
    pub fn new() -> GithubComArgoprojArgoEventsPkgApisEventsV1alpha1SensorStatus {
        GithubComArgoprojArgoEventsPkgApisEventsV1alpha1SensorStatus {
            status: None,
        }
    }
}

