/*
 * Argo Workflows API
 *
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argo-workflows.readthedocs.io/en/latest/
 *
 * The version of the OpenAPI document: VERSION
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GithubComArgoprojArgoEventsPkgApisEventsV1alpha1GithubAppCreds {
    #[serde(rename = "appID", skip_serializing_if = "Option::is_none")]
    pub app_id: Option<String>,
    #[serde(rename = "installationID", skip_serializing_if = "Option::is_none")]
    pub installation_id: Option<String>,
    #[serde(rename = "privateKey", skip_serializing_if = "Option::is_none")]
    pub private_key: Option<Box<models::IoK8sApiCoreV1SecretKeySelector>>,
}

impl GithubComArgoprojArgoEventsPkgApisEventsV1alpha1GithubAppCreds {
    pub fn new() -> GithubComArgoprojArgoEventsPkgApisEventsV1alpha1GithubAppCreds {
        GithubComArgoprojArgoEventsPkgApisEventsV1alpha1GithubAppCreds {
            app_id: None,
            installation_id: None,
            private_key: None,
        }
    }
}

