/*
 * Argo Workflows API
 *
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argo-workflows.readthedocs.io/en/latest/
 *
 * The version of the OpenAPI document: VERSION
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GithubComArgoprojArgoEventsPkgApisEventsV1alpha1NatsAuth {
    #[serde(rename = "basic", skip_serializing_if = "Option::is_none")]
    pub basic: Option<Box<models::GithubComArgoprojArgoEventsPkgApisEventsV1alpha1BasicAuth>>,
    #[serde(rename = "credential", skip_serializing_if = "Option::is_none")]
    pub credential: Option<Box<models::IoK8sApiCoreV1SecretKeySelector>>,
    #[serde(rename = "nkey", skip_serializing_if = "Option::is_none")]
    pub nkey: Option<Box<models::IoK8sApiCoreV1SecretKeySelector>>,
    #[serde(rename = "token", skip_serializing_if = "Option::is_none")]
    pub token: Option<Box<models::IoK8sApiCoreV1SecretKeySelector>>,
}

impl GithubComArgoprojArgoEventsPkgApisEventsV1alpha1NatsAuth {
    pub fn new() -> GithubComArgoprojArgoEventsPkgApisEventsV1alpha1NatsAuth {
        GithubComArgoprojArgoEventsPkgApisEventsV1alpha1NatsAuth {
            basic: None,
            credential: None,
            nkey: None,
            token: None,
        }
    }
}

