/*
 * Argo Workflows API
 *
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argo-workflows.readthedocs.io/en/latest/
 *
 * The version of the OpenAPI document: VERSION
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GithubComArgoprojArgoEventsPkgApisEventsV1alpha1BitbucketEventSource {
    #[serde(rename = "auth", skip_serializing_if = "Option::is_none")]
    pub auth: Option<Box<models::GithubComArgoprojArgoEventsPkgApisEventsV1alpha1BitbucketAuth>>,
    #[serde(rename = "deleteHookOnFinish", skip_serializing_if = "Option::is_none")]
    pub delete_hook_on_finish: Option<bool>,
    /// Events this webhook is subscribed to.
    #[serde(rename = "events", skip_serializing_if = "Option::is_none")]
    pub events: Option<Vec<String>>,
    #[serde(rename = "filter", skip_serializing_if = "Option::is_none")]
    pub filter: Option<Box<models::GithubComArgoprojArgoEventsPkgApisEventsV1alpha1EventSourceFilter>>,
    #[serde(rename = "metadata", skip_serializing_if = "Option::is_none")]
    pub metadata: Option<std::collections::HashMap<String, String>>,
    #[serde(rename = "owner", skip_serializing_if = "Option::is_none")]
    pub owner: Option<String>,
    #[serde(rename = "projectKey", skip_serializing_if = "Option::is_none")]
    pub project_key: Option<String>,
    #[serde(rename = "repositories", skip_serializing_if = "Option::is_none")]
    pub repositories: Option<Vec<models::GithubComArgoprojArgoEventsPkgApisEventsV1alpha1BitbucketRepository>>,
    #[serde(rename = "repositorySlug", skip_serializing_if = "Option::is_none")]
    pub repository_slug: Option<String>,
    #[serde(rename = "webhook", skip_serializing_if = "Option::is_none")]
    pub webhook: Option<Box<models::GithubComArgoprojArgoEventsPkgApisEventsV1alpha1WebhookContext>>,
}

impl GithubComArgoprojArgoEventsPkgApisEventsV1alpha1BitbucketEventSource {
    pub fn new() -> GithubComArgoprojArgoEventsPkgApisEventsV1alpha1BitbucketEventSource {
        GithubComArgoprojArgoEventsPkgApisEventsV1alpha1BitbucketEventSource {
            auth: None,
            delete_hook_on_finish: None,
            events: None,
            filter: None,
            metadata: None,
            owner: None,
            project_key: None,
            repositories: None,
            repository_slug: None,
            webhook: None,
        }
    }
}

