/*
 * Argo Workflows API
 *
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argo-workflows.readthedocs.io/en/latest/
 *
 * The version of the OpenAPI document: VERSION
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GithubComArgoprojArgoEventsPkgApisEventsV1alpha1SlackEventSource {
    #[serde(rename = "filter", skip_serializing_if = "Option::is_none")]
    pub filter: Option<Box<models::GithubComArgoprojArgoEventsPkgApisEventsV1alpha1EventSourceFilter>>,
    #[serde(rename = "metadata", skip_serializing_if = "Option::is_none")]
    pub metadata: Option<std::collections::HashMap<String, String>>,
    #[serde(rename = "signingSecret", skip_serializing_if = "Option::is_none")]
    pub signing_secret: Option<Box<models::IoK8sApiCoreV1SecretKeySelector>>,
    #[serde(rename = "token", skip_serializing_if = "Option::is_none")]
    pub token: Option<Box<models::IoK8sApiCoreV1SecretKeySelector>>,
    #[serde(rename = "webhook", skip_serializing_if = "Option::is_none")]
    pub webhook: Option<Box<models::GithubComArgoprojArgoEventsPkgApisEventsV1alpha1WebhookContext>>,
}

impl GithubComArgoprojArgoEventsPkgApisEventsV1alpha1SlackEventSource {
    pub fn new() -> GithubComArgoprojArgoEventsPkgApisEventsV1alpha1SlackEventSource {
        GithubComArgoprojArgoEventsPkgApisEventsV1alpha1SlackEventSource {
            filter: None,
            metadata: None,
            signing_secret: None,
            token: None,
            webhook: None,
        }
    }
}

