/*
 * Argo Workflows API
 *
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argo-workflows.readthedocs.io/en/latest/
 *
 * The version of the OpenAPI document: VERSION
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GithubComArgoprojArgoEventsPkgApisEventsV1alpha1WatchPathConfig {
    #[serde(rename = "directory", skip_serializing_if = "Option::is_none")]
    pub directory: Option<String>,
    #[serde(rename = "path", skip_serializing_if = "Option::is_none")]
    pub path: Option<String>,
    #[serde(rename = "pathRegexp", skip_serializing_if = "Option::is_none")]
    pub path_regexp: Option<String>,
}

impl GithubComArgoprojArgoEventsPkgApisEventsV1alpha1WatchPathConfig {
    pub fn new() -> GithubComArgoprojArgoEventsPkgApisEventsV1alpha1WatchPathConfig {
        GithubComArgoprojArgoEventsPkgApisEventsV1alpha1WatchPathConfig {
            directory: None,
            path: None,
            path_regexp: None,
        }
    }
}

