/*
 * Argo Workflows API
 *
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argo-workflows.readthedocs.io/en/latest/
 *
 * The version of the OpenAPI document: VERSION
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GithubComArgoprojArgoEventsPkgApisEventsV1alpha1WebhookEventSource {
    #[serde(rename = "filter", skip_serializing_if = "Option::is_none")]
    pub filter: Option<Box<models::GithubComArgoprojArgoEventsPkgApisEventsV1alpha1EventSourceFilter>>,
    #[serde(rename = "webhookContext", skip_serializing_if = "Option::is_none")]
    pub webhook_context: Option<Box<models::GithubComArgoprojArgoEventsPkgApisEventsV1alpha1WebhookContext>>,
}

impl GithubComArgoprojArgoEventsPkgApisEventsV1alpha1WebhookEventSource {
    pub fn new() -> GithubComArgoprojArgoEventsPkgApisEventsV1alpha1WebhookEventSource {
        GithubComArgoprojArgoEventsPkgApisEventsV1alpha1WebhookEventSource {
            filter: None,
            webhook_context: None,
        }
    }
}

