/*
 * Argo Workflows API
 *
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argo-workflows.readthedocs.io/en/latest/
 *
 * The version of the OpenAPI document: VERSION
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// GithubComArgoprojArgoEventsPkgApisEventsV1alpha1SlackTrigger : SlackTrigger refers to the specification of the slack notification trigger.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GithubComArgoprojArgoEventsPkgApisEventsV1alpha1SlackTrigger {
    #[serde(rename = "attachments", skip_serializing_if = "Option::is_none")]
    pub attachments: Option<String>,
    #[serde(rename = "blocks", skip_serializing_if = "Option::is_none")]
    pub blocks: Option<String>,
    #[serde(rename = "channel", skip_serializing_if = "Option::is_none")]
    pub channel: Option<String>,
    #[serde(rename = "message", skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
    #[serde(rename = "parameters", skip_serializing_if = "Option::is_none")]
    pub parameters: Option<Vec<models::GithubComArgoprojArgoEventsPkgApisEventsV1alpha1TriggerParameter>>,
    #[serde(rename = "sender", skip_serializing_if = "Option::is_none")]
    pub sender: Option<Box<models::GithubComArgoprojArgoEventsPkgApisEventsV1alpha1SlackSender>>,
    #[serde(rename = "slackToken", skip_serializing_if = "Option::is_none")]
    pub slack_token: Option<Box<models::IoK8sApiCoreV1SecretKeySelector>>,
    #[serde(rename = "thread", skip_serializing_if = "Option::is_none")]
    pub thread: Option<Box<models::GithubComArgoprojArgoEventsPkgApisEventsV1alpha1SlackThread>>,
}

impl GithubComArgoprojArgoEventsPkgApisEventsV1alpha1SlackTrigger {
    /// SlackTrigger refers to the specification of the slack notification trigger.
    pub fn new() -> GithubComArgoprojArgoEventsPkgApisEventsV1alpha1SlackTrigger {
        GithubComArgoprojArgoEventsPkgApisEventsV1alpha1SlackTrigger {
            attachments: None,
            blocks: None,
            channel: None,
            message: None,
            parameters: None,
            sender: None,
            slack_token: None,
            thread: None,
        }
    }
}

