/*
 * Argo Workflows API
 *
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argo-workflows.readthedocs.io/en/latest/
 *
 * The version of the OpenAPI document: VERSION
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GithubComArgoprojArgoEventsPkgApisEventsV1alpha1ConfigMapPersistence {
    #[serde(rename = "createIfNotExist", skip_serializing_if = "Option::is_none")]
    pub create_if_not_exist: Option<bool>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
}

impl GithubComArgoprojArgoEventsPkgApisEventsV1alpha1ConfigMapPersistence {
    pub fn new() -> GithubComArgoprojArgoEventsPkgApisEventsV1alpha1ConfigMapPersistence {
        GithubComArgoprojArgoEventsPkgApisEventsV1alpha1ConfigMapPersistence {
            create_if_not_exist: None,
            name: None,
        }
    }
}

