/*
 * Argo Workflows API
 *
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argo-workflows.readthedocs.io/en/latest/
 *
 * The version of the OpenAPI document: VERSION
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GithubComArgoprojArgoEventsPkgApisEventsV1alpha1ArtifactLocation {
    #[serde(rename = "configmap", skip_serializing_if = "Option::is_none")]
    pub configmap: Option<Box<models::IoK8sApiCoreV1ConfigMapKeySelector>>,
    #[serde(rename = "file", skip_serializing_if = "Option::is_none")]
    pub file: Option<Box<models::GithubComArgoprojArgoEventsPkgApisEventsV1alpha1FileArtifact>>,
    #[serde(rename = "git", skip_serializing_if = "Option::is_none")]
    pub git: Option<Box<models::GithubComArgoprojArgoEventsPkgApisEventsV1alpha1GitArtifact>>,
    #[serde(rename = "inline", skip_serializing_if = "Option::is_none")]
    pub inline: Option<String>,
    #[serde(rename = "resource", skip_serializing_if = "Option::is_none")]
    pub resource: Option<Box<models::GithubComArgoprojArgoEventsPkgApisEventsV1alpha1K8SResource>>,
    #[serde(rename = "s3", skip_serializing_if = "Option::is_none")]
    pub s3: Option<Box<models::GithubComArgoprojArgoEventsPkgApisEventsV1alpha1S3Artifact>>,
    #[serde(rename = "url", skip_serializing_if = "Option::is_none")]
    pub url: Option<Box<models::GithubComArgoprojArgoEventsPkgApisEventsV1alpha1UrlArtifact>>,
}

impl GithubComArgoprojArgoEventsPkgApisEventsV1alpha1ArtifactLocation {
    pub fn new() -> GithubComArgoprojArgoEventsPkgApisEventsV1alpha1ArtifactLocation {
        GithubComArgoprojArgoEventsPkgApisEventsV1alpha1ArtifactLocation {
            configmap: None,
            file: None,
            git: None,
            inline: None,
            resource: None,
            s3: None,
            url: None,
        }
    }
}

