/*
 * Argo Workflows API
 *
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argo-workflows.readthedocs.io/en/latest/
 *
 * The version of the OpenAPI document: VERSION
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GithubComArgoprojArgoEventsPkgApisEventsV1alpha1StorageGridFilter {
    #[serde(rename = "prefix", skip_serializing_if = "Option::is_none")]
    pub prefix: Option<String>,
    #[serde(rename = "suffix", skip_serializing_if = "Option::is_none")]
    pub suffix: Option<String>,
}

impl GithubComArgoprojArgoEventsPkgApisEventsV1alpha1StorageGridFilter {
    pub fn new() -> GithubComArgoprojArgoEventsPkgApisEventsV1alpha1StorageGridFilter {
        GithubComArgoprojArgoEventsPkgApisEventsV1alpha1StorageGridFilter {
            prefix: None,
            suffix: None,
        }
    }
}

