/*
 * Argo Workflows API
 *
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argo-workflows.readthedocs.io/en/latest/
 *
 * The version of the OpenAPI document: VERSION
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GithubComArgoprojArgoEventsPkgApisEventsV1alpha1SecureHeader {
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "valueFrom", skip_serializing_if = "Option::is_none")]
    pub value_from: Option<Box<models::GithubComArgoprojArgoEventsPkgApisEventsV1alpha1ValueFromSource>>,
}

impl GithubComArgoprojArgoEventsPkgApisEventsV1alpha1SecureHeader {
    pub fn new() -> GithubComArgoprojArgoEventsPkgApisEventsV1alpha1SecureHeader {
        GithubComArgoprojArgoEventsPkgApisEventsV1alpha1SecureHeader {
            name: None,
            value_from: None,
        }
    }
}

