/*
 * Argo Workflows API
 *
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argo-workflows.readthedocs.io/en/latest/
 *
 * The version of the OpenAPI document: VERSION
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GithubComArgoprojArgoEventsPkgApisEventsV1alpha1BitbucketAuth {
    #[serde(rename = "basic", skip_serializing_if = "Option::is_none")]
    pub basic: Option<Box<models::GithubComArgoprojArgoEventsPkgApisEventsV1alpha1BitbucketBasicAuth>>,
    #[serde(rename = "oauthToken", skip_serializing_if = "Option::is_none")]
    pub oauth_token: Option<Box<models::IoK8sApiCoreV1SecretKeySelector>>,
}

impl GithubComArgoprojArgoEventsPkgApisEventsV1alpha1BitbucketAuth {
    pub fn new() -> GithubComArgoprojArgoEventsPkgApisEventsV1alpha1BitbucketAuth {
        GithubComArgoprojArgoEventsPkgApisEventsV1alpha1BitbucketAuth {
            basic: None,
            oauth_token: None,
        }
    }
}

