/*
 * Argo Workflows API
 *
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argo-workflows.readthedocs.io/en/latest/
 *
 * The version of the OpenAPI document: VERSION
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

use serde_with::serde_as;

#[serde_as]
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GooglePeriodProtobufPeriodAny {
    #[serde(rename = "type_url", skip_serializing_if = "Option::is_none")]
    pub type_url: Option<String>,
    #[serde_as(as = "Option<serde_with::base64::Base64>")]
    #[serde(rename = "value", skip_serializing_if = "Option::is_none")]
    pub value: Option<Vec<u8>>,
}

impl GooglePeriodProtobufPeriodAny {
    pub fn new() -> GooglePeriodProtobufPeriodAny {
        GooglePeriodProtobufPeriodAny {
            type_url: None,
            value: None,
        }
    }
}

