/*
 * Argo Workflows API
 *
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argo-workflows.readthedocs.io/en/latest/
 *
 * The version of the OpenAPI document: VERSION
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct IoArgoprojWorkflowV1alpha1SyncDatabaseRef {
    #[serde(rename = "key")]
    pub key: String,
}

impl IoArgoprojWorkflowV1alpha1SyncDatabaseRef {
    pub fn new(key: String) -> IoArgoprojWorkflowV1alpha1SyncDatabaseRef {
        IoArgoprojWorkflowV1alpha1SyncDatabaseRef {
            key,
        }
    }
}

