/*
 * Argo Workflows API
 *
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argo-workflows.readthedocs.io/en/latest/
 *
 * The version of the OpenAPI document: VERSION
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct IoArgoprojWorkflowV1alpha1ClusterWorkflowTemplateUpdateRequest {
    /// DEPRECATED: This field is ignored.
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "template", skip_serializing_if = "Option::is_none")]
    pub template: Option<Box<models::IoArgoprojWorkflowV1alpha1ClusterWorkflowTemplate>>,
}

impl IoArgoprojWorkflowV1alpha1ClusterWorkflowTemplateUpdateRequest {
    pub fn new() -> IoArgoprojWorkflowV1alpha1ClusterWorkflowTemplateUpdateRequest {
        IoArgoprojWorkflowV1alpha1ClusterWorkflowTemplateUpdateRequest {
            name: None,
            template: None,
        }
    }
}

