/*
 * Argo Workflows API
 *
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argo-workflows.readthedocs.io/en/latest/
 *
 * The version of the OpenAPI document: VERSION
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct IoArgoprojWorkflowV1alpha1WorkflowMetadata {
    #[serde(rename = "annotations", skip_serializing_if = "Option::is_none")]
    pub annotations: Option<std::collections::HashMap<String, String>>,
    #[serde(rename = "labels", skip_serializing_if = "Option::is_none")]
    pub labels: Option<std::collections::HashMap<String, String>>,
    #[serde(rename = "labelsFrom", skip_serializing_if = "Option::is_none")]
    pub labels_from: Option<std::collections::HashMap<String, models::IoArgoprojWorkflowV1alpha1LabelValueFrom>>,
}

impl IoArgoprojWorkflowV1alpha1WorkflowMetadata {
    pub fn new() -> IoArgoprojWorkflowV1alpha1WorkflowMetadata {
        IoArgoprojWorkflowV1alpha1WorkflowMetadata {
            annotations: None,
            labels: None,
            labels_from: None,
        }
    }
}

