/*
 * Argo Workflows API
 *
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argo-workflows.readthedocs.io/en/latest/
 *
 * The version of the OpenAPI document: VERSION
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct IoArgoprojWorkflowV1alpha1Submit {
    #[serde(rename = "arguments", skip_serializing_if = "Option::is_none")]
    pub arguments: Option<Box<models::IoArgoprojWorkflowV1alpha1Arguments>>,
    #[serde(rename = "metadata", skip_serializing_if = "Option::is_none")]
    pub metadata: Option<Box<models::IoK8sApimachineryPkgApisMetaV1ObjectMeta>>,
    #[serde(rename = "workflowTemplateRef")]
    pub workflow_template_ref: Box<models::IoArgoprojWorkflowV1alpha1WorkflowTemplateRef>,
}

impl IoArgoprojWorkflowV1alpha1Submit {
    pub fn new(workflow_template_ref: models::IoArgoprojWorkflowV1alpha1WorkflowTemplateRef) -> IoArgoprojWorkflowV1alpha1Submit {
        IoArgoprojWorkflowV1alpha1Submit {
            arguments: None,
            metadata: None,
            workflow_template_ref: Box::new(workflow_template_ref),
        }
    }
}

