/*
 * Argo Workflows API
 *
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argo-workflows.readthedocs.io/en/latest/
 *
 * The version of the OpenAPI document: VERSION
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// IoArgoprojWorkflowV1alpha1ClientCertAuth : ClientCertAuth holds necessary information for client authentication via certificates
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct IoArgoprojWorkflowV1alpha1ClientCertAuth {
    #[serde(rename = "clientCertSecret", skip_serializing_if = "Option::is_none")]
    pub client_cert_secret: Option<Box<models::IoK8sApiCoreV1SecretKeySelector>>,
    #[serde(rename = "clientKeySecret", skip_serializing_if = "Option::is_none")]
    pub client_key_secret: Option<Box<models::IoK8sApiCoreV1SecretKeySelector>>,
}

impl IoArgoprojWorkflowV1alpha1ClientCertAuth {
    /// ClientCertAuth holds necessary information for client authentication via certificates
    pub fn new() -> IoArgoprojWorkflowV1alpha1ClientCertAuth {
        IoArgoprojWorkflowV1alpha1ClientCertAuth {
            client_cert_secret: None,
            client_key_secret: None,
        }
    }
}

