/*
 * Argo Workflows API
 *
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argo-workflows.readthedocs.io/en/latest/
 *
 * The version of the OpenAPI document: VERSION
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// IoK8sApimachineryPkgApisMetaV1GroupVersionResource : +protobuf.options.(gogoproto.goproto_stringer)=false
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct IoK8sApimachineryPkgApisMetaV1GroupVersionResource {
    #[serde(rename = "group", skip_serializing_if = "Option::is_none")]
    pub group: Option<String>,
    #[serde(rename = "resource", skip_serializing_if = "Option::is_none")]
    pub resource: Option<String>,
    #[serde(rename = "version", skip_serializing_if = "Option::is_none")]
    pub version: Option<String>,
}

impl IoK8sApimachineryPkgApisMetaV1GroupVersionResource {
    /// +protobuf.options.(gogoproto.goproto_stringer)=false
    pub fn new() -> IoK8sApimachineryPkgApisMetaV1GroupVersionResource {
        IoK8sApimachineryPkgApisMetaV1GroupVersionResource {
            group: None,
            resource: None,
            version: None,
        }
    }
}

