/*
 * Argo Workflows API
 *
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argo-workflows.readthedocs.io/en/latest/
 *
 * The version of the OpenAPI document: VERSION
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// IoK8sApiCoreV1FlexVolumeSource : FlexVolume represents a generic volume resource that is provisioned/attached using an exec based plugin.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct IoK8sApiCoreV1FlexVolumeSource {
    /// driver is the name of the driver to use for this volume.
    #[serde(rename = "driver")]
    pub driver: String,
    /// fsType is the filesystem type to mount. Must be a filesystem type supported by the host operating system. Ex. \"ext4\", \"xfs\", \"ntfs\". The default filesystem depends on FlexVolume script.
    #[serde(rename = "fsType", skip_serializing_if = "Option::is_none")]
    pub fs_type: Option<String>,
    /// options is Optional: this field holds extra command options if any.
    #[serde(rename = "options", skip_serializing_if = "Option::is_none")]
    pub options: Option<std::collections::HashMap<String, String>>,
    /// readOnly is Optional: defaults to false (read/write). ReadOnly here will force the ReadOnly setting in VolumeMounts.
    #[serde(rename = "readOnly", skip_serializing_if = "Option::is_none")]
    pub read_only: Option<bool>,
    #[serde(rename = "secretRef", skip_serializing_if = "Option::is_none")]
    pub secret_ref: Option<Box<models::IoK8sApiCoreV1LocalObjectReference>>,
}

impl IoK8sApiCoreV1FlexVolumeSource {
    /// FlexVolume represents a generic volume resource that is provisioned/attached using an exec based plugin.
    pub fn new(driver: String) -> IoK8sApiCoreV1FlexVolumeSource {
        IoK8sApiCoreV1FlexVolumeSource {
            driver,
            fs_type: None,
            options: None,
            read_only: None,
            secret_ref: None,
        }
    }
}

