/*
 * Argo Workflows API
 *
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argo-workflows.readthedocs.io/en/latest/
 *
 * The version of the OpenAPI document: VERSION
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// IoK8sApiCoreV1Sysctl : Sysctl defines a kernel parameter to be set
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct IoK8sApiCoreV1Sysctl {
    /// Name of a property to set
    #[serde(rename = "name")]
    pub name: String,
    /// Value of a property to set
    #[serde(rename = "value")]
    pub value: String,
}

impl IoK8sApiCoreV1Sysctl {
    /// Sysctl defines a kernel parameter to be set
    pub fn new(name: String, value: String) -> IoK8sApiCoreV1Sysctl {
        IoK8sApiCoreV1Sysctl {
            name,
            value,
        }
    }
}

