/*
 * Argo Workflows API
 *
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argo-workflows.readthedocs.io/en/latest/
 *
 * The version of the OpenAPI document: VERSION
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct IoPeriodArgoprojPeriodWorkflowPeriodV1alpha1PeriodHttp {
    /// Body is content of the HTTP Request
    #[serde(rename = "body", skip_serializing_if = "Option::is_none")]
    pub body: Option<String>,
    #[serde(rename = "bodyFrom", skip_serializing_if = "Option::is_none")]
    pub body_from: Option<Box<models::IoPeriodArgoprojPeriodWorkflowPeriodV1alpha1PeriodHttpBodySource>>,
    /// Headers are an optional list of headers to send with HTTP requests
    #[serde(rename = "headers", skip_serializing_if = "Option::is_none")]
    pub headers: Option<Vec<models::IoPeriodArgoprojPeriodWorkflowPeriodV1alpha1PeriodHttpHeader>>,
    /// InsecureSkipVerify is a bool when if set to true will skip TLS verification for the HTTP client
    #[serde(rename = "insecureSkipVerify", skip_serializing_if = "Option::is_none")]
    pub insecure_skip_verify: Option<bool>,
    /// Method is HTTP methods for HTTP Request
    #[serde(rename = "method", skip_serializing_if = "Option::is_none")]
    pub method: Option<String>,
    /// SuccessCondition is an expression if evaluated to true is considered successful
    #[serde(rename = "successCondition", skip_serializing_if = "Option::is_none")]
    pub success_condition: Option<String>,
    /// TimeoutSeconds is request timeout for HTTP Request. Default is 30 seconds
    #[serde(rename = "timeoutSeconds", skip_serializing_if = "Option::is_none")]
    pub timeout_seconds: Option<i32>,
    /// URL of the HTTP Request
    #[serde(rename = "url")]
    pub url: String,
}

impl IoPeriodArgoprojPeriodWorkflowPeriodV1alpha1PeriodHttp {
    pub fn new(url: String) -> IoPeriodArgoprojPeriodWorkflowPeriodV1alpha1PeriodHttp {
        IoPeriodArgoprojPeriodWorkflowPeriodV1alpha1PeriodHttp {
            body: None,
            body_from: None,
            headers: None,
            insecure_skip_verify: None,
            method: None,
            success_condition: None,
            timeout_seconds: None,
            url,
        }
    }
}

