/*
 * Argo Workflows API
 *
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argo-workflows.readthedocs.io/en/latest/
 *
 * The version of the OpenAPI document: VERSION
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct IoPeriodArgoprojPeriodWorkflowPeriodV1alpha1PeriodManifestFrom {
    #[serde(rename = "artifact")]
    pub artifact: Box<models::IoPeriodArgoprojPeriodWorkflowPeriodV1alpha1PeriodArtifact>,
}

impl IoPeriodArgoprojPeriodWorkflowPeriodV1alpha1PeriodManifestFrom {
    pub fn new(artifact: models::IoPeriodArgoprojPeriodWorkflowPeriodV1alpha1PeriodArtifact) -> IoPeriodArgoprojPeriodWorkflowPeriodV1alpha1PeriodManifestFrom {
        IoPeriodArgoprojPeriodWorkflowPeriodV1alpha1PeriodManifestFrom {
            artifact: Box::new(artifact),
        }
    }
}

