/*
 * Argo Workflows API
 *
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argo-workflows.readthedocs.io/en/latest/
 *
 * The version of the OpenAPI document: VERSION
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// IoPeriodArgoprojPeriodWorkflowPeriodV1alpha1PeriodWorkflowStep : WorkflowStep is a reference to a template to execute in a series of step
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct IoPeriodArgoprojPeriodWorkflowPeriodV1alpha1PeriodWorkflowStep {
    #[serde(rename = "arguments", skip_serializing_if = "Option::is_none")]
    pub arguments: Option<Box<models::IoPeriodArgoprojPeriodWorkflowPeriodV1alpha1PeriodArguments>>,
    #[serde(rename = "continueOn", skip_serializing_if = "Option::is_none")]
    pub continue_on: Option<Box<models::IoPeriodArgoprojPeriodWorkflowPeriodV1alpha1PeriodContinueOn>>,
    /// Hooks holds the lifecycle hook which is invoked at lifecycle of step, irrespective of the success, failure, or error status of the primary step
    #[serde(rename = "hooks", skip_serializing_if = "Option::is_none")]
    pub hooks: Option<std::collections::HashMap<String, models::IoPeriodArgoprojPeriodWorkflowPeriodV1alpha1PeriodLifecycleHook>>,
    #[serde(rename = "inline", skip_serializing_if = "Option::is_none")]
    pub inline: Option<Box<models::IoPeriodArgoprojPeriodWorkflowPeriodV1alpha1PeriodTemplate>>,
    /// Name of the step
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// OnExit is a template reference which is invoked at the end of the template, irrespective of the success, failure, or error of the primary template. DEPRECATED: Use Hooks[exit].Template instead.
    #[serde(rename = "onExit", skip_serializing_if = "Option::is_none")]
    pub on_exit: Option<String>,
    /// Template is the name of the template to execute as the step
    #[serde(rename = "template", skip_serializing_if = "Option::is_none")]
    pub template: Option<String>,
    #[serde(rename = "templateRef", skip_serializing_if = "Option::is_none")]
    pub template_ref: Option<Box<models::IoPeriodArgoprojPeriodWorkflowPeriodV1alpha1PeriodTemplateRef>>,
    /// When is an expression in which the step should conditionally execute
    #[serde(rename = "when", skip_serializing_if = "Option::is_none")]
    pub when: Option<String>,
    /// WithItems expands a step into multiple parallel steps from the items in the list Note: The structure of WithItems is free-form, so we need \"x-kubernetes-preserve-unknown-fields: true\" in the validation schema.
    #[serde(rename = "withItems", skip_serializing_if = "Option::is_none")]
    pub with_items: Option<Vec<serde_json::Value>>,
    /// WithParam expands a step into multiple parallel steps from the value in the parameter, which is expected to be a JSON list.
    #[serde(rename = "withParam", skip_serializing_if = "Option::is_none")]
    pub with_param: Option<String>,
    #[serde(rename = "withSequence", skip_serializing_if = "Option::is_none")]
    pub with_sequence: Option<Box<models::IoPeriodArgoprojPeriodWorkflowPeriodV1alpha1PeriodSequence>>,
}

impl IoPeriodArgoprojPeriodWorkflowPeriodV1alpha1PeriodWorkflowStep {
    /// WorkflowStep is a reference to a template to execute in a series of step
    pub fn new() -> IoPeriodArgoprojPeriodWorkflowPeriodV1alpha1PeriodWorkflowStep {
        IoPeriodArgoprojPeriodWorkflowPeriodV1alpha1PeriodWorkflowStep {
            arguments: None,
            continue_on: None,
            hooks: None,
            inline: None,
            name: None,
            on_exit: None,
            template: None,
            template_ref: None,
            when: None,
            with_items: None,
            with_param: None,
            with_sequence: None,
        }
    }
}

