/*
 * Argo Workflows API
 *
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argo-workflows.readthedocs.io/en/latest/
 *
 * The version of the OpenAPI document: VERSION
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// IoPeriodArgoprojPeriodWorkflowPeriodV1alpha1PeriodDataSource : DataSource sources external data into a data template
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct IoPeriodArgoprojPeriodWorkflowPeriodV1alpha1PeriodDataSource {
    #[serde(rename = "artifactPaths", skip_serializing_if = "Option::is_none")]
    pub artifact_paths: Option<Box<models::IoPeriodArgoprojPeriodWorkflowPeriodV1alpha1PeriodArtifactPaths>>,
}

impl IoPeriodArgoprojPeriodWorkflowPeriodV1alpha1PeriodDataSource {
    /// DataSource sources external data into a data template
    pub fn new() -> IoPeriodArgoprojPeriodWorkflowPeriodV1alpha1PeriodDataSource {
        IoPeriodArgoprojPeriodWorkflowPeriodV1alpha1PeriodDataSource {
            artifact_paths: None,
        }
    }
}

