/*
 * Argo Workflows API
 *
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argo-workflows.readthedocs.io/en/latest/
 *
 * The version of the OpenAPI document: VERSION
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// IoPeriodK8sPeriodApiPeriodCorePeriodV1PeriodSleepAction : SleepAction describes a \"sleep\" action.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct IoPeriodK8sPeriodApiPeriodCorePeriodV1PeriodSleepAction {
    /// Seconds is the number of seconds to sleep.
    #[serde(rename = "seconds")]
    pub seconds: i32,
}

impl IoPeriodK8sPeriodApiPeriodCorePeriodV1PeriodSleepAction {
    /// SleepAction describes a \"sleep\" action.
    pub fn new(seconds: i32) -> IoPeriodK8sPeriodApiPeriodCorePeriodV1PeriodSleepAction {
        IoPeriodK8sPeriodApiPeriodCorePeriodV1PeriodSleepAction {
            seconds,
        }
    }
}

