/*
 * Argo Workflows API
 *
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argo-workflows.readthedocs.io/en/latest/
 *
 * The version of the OpenAPI document: VERSION
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// IoPeriodArgoprojPeriodWorkflowPeriodV1alpha1PeriodMetricLabel : MetricLabel is a single label for a prometheus metric
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct IoPeriodArgoprojPeriodWorkflowPeriodV1alpha1PeriodMetricLabel {
    #[serde(rename = "key")]
    pub key: String,
    #[serde(rename = "value")]
    pub value: String,
}

impl IoPeriodArgoprojPeriodWorkflowPeriodV1alpha1PeriodMetricLabel {
    /// MetricLabel is a single label for a prometheus metric
    pub fn new(key: String, value: String) -> IoPeriodArgoprojPeriodWorkflowPeriodV1alpha1PeriodMetricLabel {
        IoPeriodArgoprojPeriodWorkflowPeriodV1alpha1PeriodMetricLabel {
            key,
            value,
        }
    }
}

