/*
 * Argo Workflows API
 *
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argo-workflows.readthedocs.io/en/latest/
 *
 * The version of the OpenAPI document: VERSION
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// IoPeriodArgoprojPeriodWorkflowPeriodV1alpha1PeriodNodeSynchronizationStatus : NodeSynchronizationStatus stores the status of a node
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct IoPeriodArgoprojPeriodWorkflowPeriodV1alpha1PeriodNodeSynchronizationStatus {
    /// Waiting is the name of the lock that this node is waiting for
    #[serde(rename = "waiting", skip_serializing_if = "Option::is_none")]
    pub waiting: Option<String>,
}

impl IoPeriodArgoprojPeriodWorkflowPeriodV1alpha1PeriodNodeSynchronizationStatus {
    /// NodeSynchronizationStatus stores the status of a node
    pub fn new() -> IoPeriodArgoprojPeriodWorkflowPeriodV1alpha1PeriodNodeSynchronizationStatus {
        IoPeriodArgoprojPeriodWorkflowPeriodV1alpha1PeriodNodeSynchronizationStatus {
            waiting: None,
        }
    }
}

