/*
 * Argo Workflows API
 *
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argo-workflows.readthedocs.io/en/latest/
 *
 * The version of the OpenAPI document: VERSION
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// IoPeriodArgoprojPeriodWorkflowPeriodV1alpha1PeriodPrometheus : Prometheus is a prometheus metric to be emitted
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct IoPeriodArgoprojPeriodWorkflowPeriodV1alpha1PeriodPrometheus {
    #[serde(rename = "counter", skip_serializing_if = "Option::is_none")]
    pub counter: Option<Box<models::IoPeriodArgoprojPeriodWorkflowPeriodV1alpha1PeriodCounter>>,
    #[serde(rename = "gauge", skip_serializing_if = "Option::is_none")]
    pub gauge: Option<Box<models::IoPeriodArgoprojPeriodWorkflowPeriodV1alpha1PeriodGauge>>,
    /// Help is a string that describes the metric
    #[serde(rename = "help")]
    pub help: String,
    #[serde(rename = "histogram", skip_serializing_if = "Option::is_none")]
    pub histogram: Option<Box<models::IoPeriodArgoprojPeriodWorkflowPeriodV1alpha1PeriodHistogram>>,
    /// Labels is a list of metric labels
    #[serde(rename = "labels", skip_serializing_if = "Option::is_none")]
    pub labels: Option<Vec<models::IoPeriodArgoprojPeriodWorkflowPeriodV1alpha1PeriodMetricLabel>>,
    /// Name is the name of the metric
    #[serde(rename = "name")]
    pub name: String,
    /// When is a conditional statement that decides when to emit the metric
    #[serde(rename = "when", skip_serializing_if = "Option::is_none")]
    pub when: Option<String>,
}

impl IoPeriodArgoprojPeriodWorkflowPeriodV1alpha1PeriodPrometheus {
    /// Prometheus is a prometheus metric to be emitted
    pub fn new(help: String, name: String) -> IoPeriodArgoprojPeriodWorkflowPeriodV1alpha1PeriodPrometheus {
        IoPeriodArgoprojPeriodWorkflowPeriodV1alpha1PeriodPrometheus {
            counter: None,
            gauge: None,
            help,
            histogram: None,
            labels: None,
            name,
            when: None,
        }
    }
}

