/*
 * Argo Workflows API
 *
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argo-workflows.readthedocs.io/en/latest/
 *
 * The version of the OpenAPI document: VERSION
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// IoPeriodK8sPeriodApiPeriodCorePeriodV1PeriodVolumeProjection : Projection that may be projected along with other supported volume types. Exactly one of these fields must be set.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct IoPeriodK8sPeriodApiPeriodCorePeriodV1PeriodVolumeProjection {
    #[serde(rename = "clusterTrustBundle", skip_serializing_if = "Option::is_none")]
    pub cluster_trust_bundle: Option<Box<models::IoPeriodK8sPeriodApiPeriodCorePeriodV1PeriodClusterTrustBundleProjection>>,
    #[serde(rename = "configMap", skip_serializing_if = "Option::is_none")]
    pub config_map: Option<Box<models::IoPeriodK8sPeriodApiPeriodCorePeriodV1PeriodConfigMapProjection>>,
    #[serde(rename = "downwardAPI", skip_serializing_if = "Option::is_none")]
    pub downward_api: Option<Box<models::IoPeriodK8sPeriodApiPeriodCorePeriodV1PeriodDownwardApiProjection>>,
    #[serde(rename = "secret", skip_serializing_if = "Option::is_none")]
    pub secret: Option<Box<models::IoPeriodK8sPeriodApiPeriodCorePeriodV1PeriodSecretProjection>>,
    #[serde(rename = "serviceAccountToken", skip_serializing_if = "Option::is_none")]
    pub service_account_token: Option<Box<models::IoPeriodK8sPeriodApiPeriodCorePeriodV1PeriodServiceAccountTokenProjection>>,
}

impl IoPeriodK8sPeriodApiPeriodCorePeriodV1PeriodVolumeProjection {
    /// Projection that may be projected along with other supported volume types. Exactly one of these fields must be set.
    pub fn new() -> IoPeriodK8sPeriodApiPeriodCorePeriodV1PeriodVolumeProjection {
        IoPeriodK8sPeriodApiPeriodCorePeriodV1PeriodVolumeProjection {
            cluster_trust_bundle: None,
            config_map: None,
            downward_api: None,
            secret: None,
            service_account_token: None,
        }
    }
}

