/*
 * Argo Workflows API
 *
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argo-workflows.readthedocs.io/en/latest/
 *
 * The version of the OpenAPI document: VERSION
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// IoPeriodArgoprojPeriodWorkflowPeriodV1alpha1PeriodHttpArtifact : HTTPArtifact allows a file served on HTTP to be placed as an input artifact in a container
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct IoPeriodArgoprojPeriodWorkflowPeriodV1alpha1PeriodHttpArtifact {
    #[serde(rename = "auth", skip_serializing_if = "Option::is_none")]
    pub auth: Option<Box<models::IoPeriodArgoprojPeriodWorkflowPeriodV1alpha1PeriodHttpAuth>>,
    /// Headers are an optional list of headers to send with HTTP requests for artifacts
    #[serde(rename = "headers", skip_serializing_if = "Option::is_none")]
    pub headers: Option<Vec<models::IoPeriodArgoprojPeriodWorkflowPeriodV1alpha1PeriodHeader>>,
    /// URL of the artifact
    #[serde(rename = "url")]
    pub url: String,
}

impl IoPeriodArgoprojPeriodWorkflowPeriodV1alpha1PeriodHttpArtifact {
    /// HTTPArtifact allows a file served on HTTP to be placed as an input artifact in a container
    pub fn new(url: String) -> IoPeriodArgoprojPeriodWorkflowPeriodV1alpha1PeriodHttpArtifact {
        IoPeriodArgoprojPeriodWorkflowPeriodV1alpha1PeriodHttpArtifact {
            auth: None,
            headers: None,
            url,
        }
    }
}

