/*
 * Argo Workflows API
 *
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argo-workflows.readthedocs.io/en/latest/
 *
 * The version of the OpenAPI document: VERSION
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// IoPeriodArgoprojPeriodWorkflowPeriodV1alpha1PeriodAzureArtifactRepository : AzureArtifactRepository defines the controller configuration for an Azure Blob Storage artifact repository
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct IoPeriodArgoprojPeriodWorkflowPeriodV1alpha1PeriodAzureArtifactRepository {
    #[serde(rename = "accountKeySecret", skip_serializing_if = "Option::is_none")]
    pub account_key_secret: Option<Box<models::IoPeriodK8sPeriodApiPeriodCorePeriodV1PeriodSecretKeySelector>>,
    /// BlobNameFormat is defines the format of how to store blob names. Can reference workflow variables
    #[serde(rename = "blobNameFormat", skip_serializing_if = "Option::is_none")]
    pub blob_name_format: Option<String>,
    /// Container is the container where resources will be stored
    #[serde(rename = "container")]
    pub container: String,
    /// Endpoint is the service url associated with an account. It is most likely \"https://<ACCOUNT_NAME>.blob.core.windows.net\"
    #[serde(rename = "endpoint")]
    pub endpoint: String,
    /// UseSDKCreds tells the driver to figure out credentials based on sdk defaults.
    #[serde(rename = "useSDKCreds", skip_serializing_if = "Option::is_none")]
    pub use_sdk_creds: Option<bool>,
}

impl IoPeriodArgoprojPeriodWorkflowPeriodV1alpha1PeriodAzureArtifactRepository {
    /// AzureArtifactRepository defines the controller configuration for an Azure Blob Storage artifact repository
    pub fn new(container: String, endpoint: String) -> IoPeriodArgoprojPeriodWorkflowPeriodV1alpha1PeriodAzureArtifactRepository {
        IoPeriodArgoprojPeriodWorkflowPeriodV1alpha1PeriodAzureArtifactRepository {
            account_key_secret: None,
            blob_name_format: None,
            container,
            endpoint,
            use_sdk_creds: None,
        }
    }
}

