/*
 * Argo Workflows API
 *
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argo-workflows.readthedocs.io/en/latest/
 *
 * The version of the OpenAPI document: VERSION
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// IoPeriodArgoprojPeriodWorkflowPeriodV1alpha1PeriodCreateS3BucketOptions : CreateS3BucketOptions options used to determine automatic automatic bucket-creation process
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct IoPeriodArgoprojPeriodWorkflowPeriodV1alpha1PeriodCreateS3BucketOptions {
    /// ObjectLocking Enable object locking
    #[serde(rename = "objectLocking", skip_serializing_if = "Option::is_none")]
    pub object_locking: Option<bool>,
}

impl IoPeriodArgoprojPeriodWorkflowPeriodV1alpha1PeriodCreateS3BucketOptions {
    /// CreateS3BucketOptions options used to determine automatic automatic bucket-creation process
    pub fn new() -> IoPeriodArgoprojPeriodWorkflowPeriodV1alpha1PeriodCreateS3BucketOptions {
        IoPeriodArgoprojPeriodWorkflowPeriodV1alpha1PeriodCreateS3BucketOptions {
            object_locking: None,
        }
    }
}

