/*
 * Argo Workflows API
 *
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argo-workflows.readthedocs.io/en/latest/
 *
 * The version of the OpenAPI document: VERSION
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

use serde_with::serde_as;

/// IoPeriodArgoprojPeriodWorkflowPeriodV1alpha1PeriodHttpBodySource : HTTPBodySource contains the source of the HTTP body.
#[serde_as]
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct IoPeriodArgoprojPeriodWorkflowPeriodV1alpha1PeriodHttpBodySource {
    #[serde_as(as = "Option<serde_with::base64::Base64>")]
    #[serde(rename = "bytes", skip_serializing_if = "Option::is_none")]
    pub bytes: Option<Vec<u8>>,
}

impl IoPeriodArgoprojPeriodWorkflowPeriodV1alpha1PeriodHttpBodySource {
    /// HTTPBodySource contains the source of the HTTP body.
    pub fn new() -> IoPeriodArgoprojPeriodWorkflowPeriodV1alpha1PeriodHttpBodySource {
        IoPeriodArgoprojPeriodWorkflowPeriodV1alpha1PeriodHttpBodySource {
            bytes: None,
        }
    }
}

