/*
 * Argo Workflows API
 *
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argo-workflows.readthedocs.io/en/latest/
 *
 * The version of the OpenAPI document: VERSION
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// IoPeriodK8sPeriodApiPeriodCorePeriodV1PeriodPreferredSchedulingTerm : An empty preferred scheduling term matches all objects with implicit weight 0 (i.e. it's a no-op). A null preferred scheduling term matches no objects (i.e. is also a no-op).
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct IoPeriodK8sPeriodApiPeriodCorePeriodV1PeriodPreferredSchedulingTerm {
    #[serde(rename = "preference")]
    pub preference: Box<models::IoPeriodK8sPeriodApiPeriodCorePeriodV1PeriodNodeSelectorTerm>,
    /// Weight associated with matching the corresponding nodeSelectorTerm, in the range 1-100.
    #[serde(rename = "weight")]
    pub weight: i32,
}

impl IoPeriodK8sPeriodApiPeriodCorePeriodV1PeriodPreferredSchedulingTerm {
    /// An empty preferred scheduling term matches all objects with implicit weight 0 (i.e. it's a no-op). A null preferred scheduling term matches no objects (i.e. is also a no-op).
    pub fn new(preference: models::IoPeriodK8sPeriodApiPeriodCorePeriodV1PeriodNodeSelectorTerm, weight: i32) -> IoPeriodK8sPeriodApiPeriodCorePeriodV1PeriodPreferredSchedulingTerm {
        IoPeriodK8sPeriodApiPeriodCorePeriodV1PeriodPreferredSchedulingTerm {
            preference: Box::new(preference),
            weight,
        }
    }
}

