/*
 * Argo Workflows API
 *
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argo-workflows.readthedocs.io/en/latest/
 *
 * The version of the OpenAPI document: VERSION
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// IoPeriodArgoprojPeriodWorkflowPeriodV1alpha1PeriodSemaphoreRef : SemaphoreRef is a reference of Semaphore
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct IoPeriodArgoprojPeriodWorkflowPeriodV1alpha1PeriodSemaphoreRef {
    #[serde(rename = "configMapKeyRef", skip_serializing_if = "Option::is_none")]
    pub config_map_key_ref: Option<Box<models::IoPeriodK8sPeriodApiPeriodCorePeriodV1PeriodConfigMapKeySelector>>,
    #[serde(rename = "database", skip_serializing_if = "Option::is_none")]
    pub database: Option<Box<models::IoPeriodArgoprojPeriodWorkflowPeriodV1alpha1PeriodSyncDatabaseRef>>,
    /// Namespace is the namespace of the configmap, default: [namespace of workflow]
    #[serde(rename = "namespace", skip_serializing_if = "Option::is_none")]
    pub namespace: Option<String>,
}

impl IoPeriodArgoprojPeriodWorkflowPeriodV1alpha1PeriodSemaphoreRef {
    /// SemaphoreRef is a reference of Semaphore
    pub fn new() -> IoPeriodArgoprojPeriodWorkflowPeriodV1alpha1PeriodSemaphoreRef {
        IoPeriodArgoprojPeriodWorkflowPeriodV1alpha1PeriodSemaphoreRef {
            config_map_key_ref: None,
            database: None,
            namespace: None,
        }
    }
}

