/*
 * Argo Workflows API
 *
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argo-workflows.readthedocs.io/en/latest/
 *
 * The version of the OpenAPI document: VERSION
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// IoPeriodArgoprojPeriodWorkflowPeriodV1alpha1PeriodArtifactPaths : ArtifactPaths expands a step from a collection of artifacts
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct IoPeriodArgoprojPeriodWorkflowPeriodV1alpha1PeriodArtifactPaths {
    #[serde(rename = "archive", skip_serializing_if = "Option::is_none")]
    pub archive: Option<Box<models::IoPeriodArgoprojPeriodWorkflowPeriodV1alpha1PeriodArchiveStrategy>>,
    /// ArchiveLogs indicates if the container logs should be archived
    #[serde(rename = "archiveLogs", skip_serializing_if = "Option::is_none")]
    pub archive_logs: Option<bool>,
    #[serde(rename = "artifactGC", skip_serializing_if = "Option::is_none")]
    pub artifact_gc: Option<Box<models::IoPeriodArgoprojPeriodWorkflowPeriodV1alpha1PeriodArtifactGc>>,
    #[serde(rename = "artifactory", skip_serializing_if = "Option::is_none")]
    pub artifactory: Option<Box<models::IoPeriodArgoprojPeriodWorkflowPeriodV1alpha1PeriodArtifactoryArtifact>>,
    #[serde(rename = "azure", skip_serializing_if = "Option::is_none")]
    pub azure: Option<Box<models::IoPeriodArgoprojPeriodWorkflowPeriodV1alpha1PeriodAzureArtifact>>,
    /// Has this been deleted?
    #[serde(rename = "deleted", skip_serializing_if = "Option::is_none")]
    pub deleted: Option<bool>,
    /// From allows an artifact to reference an artifact from a previous step
    #[serde(rename = "from", skip_serializing_if = "Option::is_none")]
    pub from: Option<String>,
    /// FromExpression, if defined, is evaluated to specify the value for the artifact
    #[serde(rename = "fromExpression", skip_serializing_if = "Option::is_none")]
    pub from_expression: Option<String>,
    #[serde(rename = "gcs", skip_serializing_if = "Option::is_none")]
    pub gcs: Option<Box<models::IoPeriodArgoprojPeriodWorkflowPeriodV1alpha1PeriodGcsArtifact>>,
    #[serde(rename = "git", skip_serializing_if = "Option::is_none")]
    pub git: Option<Box<models::IoPeriodArgoprojPeriodWorkflowPeriodV1alpha1PeriodGitArtifact>>,
    /// GlobalName exports an output artifact to the global scope, making it available as '{{io.argoproj.workflow.v1alpha1.outputs.artifacts.XXXX}} and in workflow.status.outputs.artifacts
    #[serde(rename = "globalName", skip_serializing_if = "Option::is_none")]
    pub global_name: Option<String>,
    #[serde(rename = "hdfs", skip_serializing_if = "Option::is_none")]
    pub hdfs: Option<Box<models::IoPeriodArgoprojPeriodWorkflowPeriodV1alpha1PeriodHdfsArtifact>>,
    #[serde(rename = "http", skip_serializing_if = "Option::is_none")]
    pub http: Option<Box<models::IoPeriodArgoprojPeriodWorkflowPeriodV1alpha1PeriodHttpArtifact>>,
    /// mode bits to use on this file, must be a value between 0 and 0777 set when loading input artifacts.
    #[serde(rename = "mode", skip_serializing_if = "Option::is_none")]
    pub mode: Option<i32>,
    /// name of the artifact. must be unique within a template's inputs/outputs.
    #[serde(rename = "name")]
    pub name: String,
    /// Make Artifacts optional, if Artifacts doesn't generate or exist
    #[serde(rename = "optional", skip_serializing_if = "Option::is_none")]
    pub optional: Option<bool>,
    #[serde(rename = "oss", skip_serializing_if = "Option::is_none")]
    pub oss: Option<Box<models::IoPeriodArgoprojPeriodWorkflowPeriodV1alpha1PeriodOssArtifact>>,
    /// Path is the container path to the artifact
    #[serde(rename = "path", skip_serializing_if = "Option::is_none")]
    pub path: Option<String>,
    #[serde(rename = "raw", skip_serializing_if = "Option::is_none")]
    pub raw: Option<Box<models::IoPeriodArgoprojPeriodWorkflowPeriodV1alpha1PeriodRawArtifact>>,
    /// If mode is set, apply the permission recursively into the artifact if it is a folder
    #[serde(rename = "recurseMode", skip_serializing_if = "Option::is_none")]
    pub recurse_mode: Option<bool>,
    #[serde(rename = "s3", skip_serializing_if = "Option::is_none")]
    pub s3: Option<Box<models::IoPeriodArgoprojPeriodWorkflowPeriodV1alpha1PeriodS3Artifact>>,
    /// SubPath allows an artifact to be sourced from a subpath within the specified source
    #[serde(rename = "subPath", skip_serializing_if = "Option::is_none")]
    pub sub_path: Option<String>,
}

impl IoPeriodArgoprojPeriodWorkflowPeriodV1alpha1PeriodArtifactPaths {
    /// ArtifactPaths expands a step from a collection of artifacts
    pub fn new(name: String) -> IoPeriodArgoprojPeriodWorkflowPeriodV1alpha1PeriodArtifactPaths {
        IoPeriodArgoprojPeriodWorkflowPeriodV1alpha1PeriodArtifactPaths {
            archive: None,
            archive_logs: None,
            artifact_gc: None,
            artifactory: None,
            azure: None,
            deleted: None,
            from: None,
            from_expression: None,
            gcs: None,
            git: None,
            global_name: None,
            hdfs: None,
            http: None,
            mode: None,
            name,
            optional: None,
            oss: None,
            path: None,
            raw: None,
            recurse_mode: None,
            s3: None,
            sub_path: None,
        }
    }
}

