/*
 * Argo Workflows API
 *
 * Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. For more information, please see https://argo-workflows.readthedocs.io/en/latest/
 *
 * The version of the OpenAPI document: VERSION
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// IoPeriodK8sPeriodApiPeriodCorePeriodV1PeriodTcpSocketAction : TCPSocketAction describes an action based on opening a socket
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct IoPeriodK8sPeriodApiPeriodCorePeriodV1PeriodTcpSocketAction {
    /// Optional: Host name to connect to, defaults to the pod IP.
    #[serde(rename = "host", skip_serializing_if = "Option::is_none")]
    pub host: Option<String>,
    #[serde(rename = "port")]
    pub port: String,
}

impl IoPeriodK8sPeriodApiPeriodCorePeriodV1PeriodTcpSocketAction {
    /// TCPSocketAction describes an action based on opening a socket
    pub fn new(port: String) -> IoPeriodK8sPeriodApiPeriodCorePeriodV1PeriodTcpSocketAction {
        IoPeriodK8sPeriodApiPeriodCorePeriodV1PeriodTcpSocketAction {
            host: None,
            port,
        }
    }
}

